"""add_document_records_table

Revision ID: 1e0fe7a2dcf7
Revises: ebd7d1cd3b60
Create Date: 2026-06-27 20:24:48.782318

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "1e0fe7a2dcf7"
down_revision = "ebd7d1cd3b60"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "document_records",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("legislation_id", sa.UUID(), nullable=False),
        sa.Column("file_url", sa.Text(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("publication_date", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("document_id"),
    )
    op.create_index(
        op.f("ix_document_records_legislation_id"),
        "document_records",
        ["legislation_id"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        op.f("ix_document_records_legislation_id"), table_name="document_records"
    )
    op.drop_table("document_records")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pending_notifications",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("crawler_type", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("entity_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.TEXT(),
            server_default=sa.text("'pending'::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pending_notifications_pkey")),
    )
    op.create_table(
        "legislation_craw",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("legislation_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "publication_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("publication_media", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("pdf_link", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("file_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("status", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("legislation_craw_pkey")),
        sa.UniqueConstraint(
            "legislation_id",
            name=op.f("legislation_craw_legislation_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "user_subscriptions",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("crawler_type", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "filters",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_subscriptions_pkey")),
    )
    op.drop_index(
        op.f("ix_document_records_legislation_id"), table_name="document_records"
    )
    op.drop_table("document_records")
    # ### end Alembic commands ###
